In [1]:
# Introduction of data
# Excluding low variance data
import pandas as pd
file_path = r'data4PF.csv'
all_data = pd.read_csv(file_path)

In [2]:
all_data

,ID,pretty_formula,pf_log,T,spacegroup,a,b,c,alpha,beta,...,min:num_s_valence,min:period,min:specific_heat,min:thermal_conductivity,min:vdw_radius,min:vdw_radius_alvarez,min:vdw_radius_mm3,min:vdw_radius_uff,min:sound_velocity,min:Polarizability
0,mp-998899,YN,-1.296850,1000,187,3.365604,3.365604,3.063359,90.000000,90.000000,...,2,2,0.284,0.02583,155,166,193,334.5,333.600000,1.10
1,mp-938,GeTe,7.452482,1000,160,4.375164,4.375164,4.375164,57.826728,57.826728,...,2,4,0.201,3.00000,206,199,244,428.0,2610.000000,5.50
2,mp-866291,AgBr,5.546150,1000,216,4.475784,4.475784,4.475784,60.000000,60.000000,...,1,4,0.237,0.12000,185,186,222,314.8,2467.612558,3.05
3,mp-830,GaN,-4.584891,1000,216,3.214208,3.214208,3.214208,60.000000,60.000000,...,2,2,0.372,0.02583,155,166,193,366.0,333.600000,1.10
4,mp-749,SmN,3.644443,1000,225,3.588021,3.588021,3.588021,60.000000,60.000000,...,2,2,0.180,0.02583,155,166,193,352.0,333.600000,1.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,mp-1009639,PrN,-4.404720,500,216,3.935348,3.935348,3.935348,60.000000,60.000000,...,2,2,0.192,0.02583,155,166,193,360.6,333.600000,1.10
398,mp-1009540,OsC,7.618568,500,216,3.261481,3.261481,3.261481,60.000000,60.000000,...,2,2,0.131,88.00000,170,177,204,312.0,4940.000000,1.67
399,mp-1007778,TlN,0.152674,500,216,3.727867,3.727867,3.727867,60.000000,60.000000,...,2,2,0.128,0.02583,155,166,193,366.0,333.600000,1.10
400,mp-1007776,TlP,-1.499308,500,216,4.327494,4.327494,4.327494,60.000000,60.000000,...,2,3,0.128,0.23600,180,190,222,414.7,818.000000,3.63
401,mp-1002124,HfC,6.078551,500,216,3.565664,3.565664,3.565664,60.000000,60.000000,...,2,2,0.146,23.00000,170,177,204,314.1,3010.000000,1.67

In [3]:
X = all_data.iloc[:,3:318]
y = all_data.iloc[:,0:3]

In [4]:
y

             ID pretty_formula    pf_log
0     mp-998899             YN -1.296850
1        mp-938           GeTe  7.452482
2     mp-866291           AgBr  5.546150
3        mp-830            GaN -4.584891
4        mp-749            SmN  3.644443
..          ...            ...       ...
397  mp-1009639            PrN -4.404720
398  mp-1009540            OsC  7.618568
399  mp-1007778            TlN  0.152674
400  mp-1007776            TlP -1.499308
401  mp-1002124            HfC  6.078551

[402 rows x 3 columns]

In [5]:
X

,T,spacegroup,a,b,c,alpha,beta,gamma,volume,volume/atom,...,min:num_s_valence,min:period,min:specific_heat,min:thermal_conductivity,min:vdw_radius,min:vdw_radius_alvarez,min:vdw_radius_mm3,min:vdw_radius_uff,min:sound_velocity,min:Polarizability
0,1000,187,3.365604,3.365604,3.063359,90.000000,90.000000,120.000007,30.050702,15.025351,...,2,2,0.284,0.02583,155,166,193,334.5,333.600000,1.10
1,1000,160,4.375164,4.375164,4.375164,57.826728,57.826728,57.826722,56.264958,28.132479,...,2,4,0.201,3.00000,206,199,244,428.0,2610.000000,5.50
2,1000,216,4.475784,4.475784,4.475784,60.000000,60.000000,60.000000,63.400440,31.700220,...,1,4,0.237,0.12000,185,186,222,314.8,2467.612558,3.05
3,1000,216,3.214208,3.214208,3.214208,60.000000,60.000000,60.000000,23.480470,11.740235,...,2,2,0.372,0.02583,155,166,193,366.0,333.600000,1.10
4,1000,225,3.588021,3.588021,3.588021,60.000000,60.000000,60.000000,32.662539,16.331269,...,2,2,0.180,0.02583,155,166,193,352.0,333.600000,1.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,500,216,3.935348,3.935348,3.935348,60.000000,60.000000,60.000000,43.095737,21.547868,...,2,2,0.192,0.02583,155,166,193,360.6,333.600000,1.10
398,500,216,3.261481,3.261481,3.261481,60.000000,60.000000,60.000000,24.531798,12.265899,...,2,2,0.131,88.00000,170,177,204,312.0,4940.000000,1.67
399,500,216,3.727867,3.727867,3.727867,60.000000,60.000000,60.000000,36.632471,18.316235,...,2,2,0.128,0.02583,155,166,193,366.0,333.600000,1.10
400,500,216,4.327494,4.327494,4.327494,60.000000,60.000000,60.000000,57.305232,28.652616,...,2,3,0.128,0.23600,180,190,222,414.7,818.000000,3.63
401,500,216,3.565664,3.565664,3.565664,60.000000,60.000000,60.000000,32.055765,16.027883,...,2,2,0.146,23.00000,170,177,204,314.1,3010.000000,1.67

In [6]:
import numpy as np
X_var = pd.DataFrame(X.var())
file_path = r'PF_data_var.csv'
X_var.to_csv(file_path, index = True)

In [7]:
from sklearn.feature_selection import VarianceThreshold
vt = VarianceThreshold(threshold = 0.01)
X_selected = vt.fit_transform(X)
lowvariance_data = pd.DataFrame(X_selected)
X_selected.shape

(402, 297)

In [8]:
all_name = X.columns.values.tolist() 
select_name_index0 = vt.get_support(indices=True) 
select_name0 = []
for i in select_name_index0:
    select_name0.append(all_name[i])

In [9]:
len(select_name0)

297

In [10]:
lowvariance_data.columns = select_name0
file_path = r'PF_data_lowvar.csv'
lowvariance_data_y = pd.concat((y,lowvariance_data),axis = 1)
lowvariance_data_y.to_csv(file_path, index = False)